export const phoneNumbers = [
  { text: 'United States', code: '+1', country: 'US' },
  { text: 'Canada', code: '+1', country: 'CA' },
  { text: 'Russia', code: '+7', country: 'RU' },
  { text: 'Egypt', code: '+20', country: 'EG' },
  { text: 'South Africa', code: '+27', country: 'ZA' },
  { text: 'Greece', code: '+30', country: 'GR' },
  { text: 'Netherlands', code: '+31', country: 'NL' },
  { text: 'Belgium', code: '+32', country: 'BE' },
  { text: 'France', code: '+33', country: 'FR' },
  { text: 'Spain', code: '+34', country: 'ES' },
  { text: 'Hungary', code: '+36', country: 'HU' },
  { text: 'Italy', code: '+39', country: 'IT' },
  { text: 'Romania', code: '+40', country: 'RO' },
  { text: 'Switzerland', code: '+41', country: 'CH' },
  { text: 'Austria', code: '+43', country: 'AT' },
  { text: 'United Kingdom', code: '+44', country: 'GB' },
  { text: 'Denmark', code: '+45', country: 'DK' },
  { text: 'Sweden', code: '+46', country: 'SE' },
  { text: 'Norway', code: '+47', country: 'NO' },
  { text: 'Poland', code: '+48', country: 'PL' },
  { text: 'Germany', code: '+49', country: 'DE' },
  { text: 'Peru', code: '+51', country: 'PE' },
  { text: 'Mexico', code: '+52', country: 'MX' },
  { text: 'Cuba', code: '+53', country: 'CU' },
  { text: 'Argentina', code: '+54', country: 'AR' },
  { text: 'Brazil', code: '+55', country: 'BR' },
  { text: 'Chile', code: '+56', country: 'CL' },
  { text: 'Colombia', code: '+57', country: 'CO' },
  { text: 'Venezuela', code: '+58', country: 'VE' },
  { text: 'Malaysia', code: '+60', country: 'MY' },
  { text: 'Australia', code: '+61', country: 'AU' },
  { text: 'Indonesia', code: '+62', country: 'ID' },
  { text: 'Philippines', code: '+63', country: 'PH' },
  { text: 'New Zealand', code: '+64', country: 'NZ' },
  { text: 'Singapore', code: '+65', country: 'SG' },
  { text: 'Thailand', code: '+66', country: 'TH' },
  { text: 'Japan', code: '+81', country: 'JP' },
  { text: 'South Korea', code: '+82', country: 'KR' },
  { text: 'Vietnam', code: '+84', country: 'VN' },
  { text: 'China', code: '+86', country: 'CN' },
  { text: 'Turkey', code: '+90', country: 'TR' },
  { text: 'India', code: '+91', country: 'IN' },
  { text: 'Pakistan', code: '+92', country: 'PK' },
  { text: 'Afghanistan', code: '+93', country: 'AF' },
  { text: 'Sri Lanka', code: '+94', country: 'LK' },
  { text: 'Myanmar', code: '+95', country: 'MM' },
  { text: 'Iran', code: '+98', country: 'IR' },
  { text: 'Morocco', code: '+212', country: 'MA' },
  { text: 'Algeria', code: '+213', country: 'DZ' },
  { text: 'Tunisia', code: '+216', country: 'TN' },
  { text: 'Libya', code: '+218', country: 'LY' },
  { text: 'Gambia', code: '+220', country: 'GM' },
  { text: 'Senegal', code: '+221', country: 'SN' },
  { text: 'Mauritania', code: '+222', country: 'MR' },
  { text: 'Mali', code: '+223', country: 'ML' },
  { text: 'Guinea', code: '+224', country: 'GN' },
  { text: 'Ivory Coast', code: '+225', country: 'CI' },
  { text: 'Burkina Faso', code: '+226', country: 'BF' },
  { text: 'Niger', code: '+227', country: 'NE' },
  { text: 'Togo', code: '+228', country: 'TG' },
  { text: 'Benin', code: '+229', country: 'BJ' },
  { text: 'Mauritius', code: '+230', country: 'MU' },
  { text: 'Liberia', code: '+231', country: 'LR' },
  { text: 'Sierra Leone', code: '+232', country: 'SL' },
  { text: 'Ghana', code: '+233', country: 'GH' },
  { text: 'Nigeria', code: '+234', country: 'NG' },
  { text: 'Chad', code: '+235', country: 'TD' },
  { text: 'Central African Republic', code: '+236', country: 'CF' },
  { text: 'Cameroon', code: '+237', country: 'CM' },
  { text: 'Cape Verde', code: '+238', country: 'CV' },
  { text: 'Sao Tome and Principe', code: '+239', country: 'ST' },
  { text: 'Equatorial Guinea', code: '+240', country: 'GQ' },
  { text: 'Gabon', code: '+241', country: 'GA' },
  { text: 'Republic of the Congo', code: '+242', country: 'CG' },
  {
    text: 'Democratic Republic of the Congo',
    code: '+243',
    country: 'CD',
  },
  { text: 'Angola', code: '+244', country: 'AO' },
  { text: 'Guinea-Bissau', code: '+245', country: 'GW' },
  {
    text: 'British Indian Ocean Territory',
    code: '+246',
    country: 'IO',
  },
  { text: 'Seychelles', code: '+248', country: 'SC' },
  { text: 'Sudan', code: '+249', country: 'SD' },
  { text: 'Rwanda', code: '+250', country: 'RW' },
  { text: 'Ethiopia', code: '+251', country: 'ET' },
  { text: 'Somalia', code: '+252', country: 'SO' },
  { text: 'Djibouti', code: '+253', country: 'DJ' },
  { text: 'Kenya', code: '+254', country: 'KE' },
  { text: 'Tanzania', code: '+255', country: 'TZ' },
  { text: 'Uganda', code: '+256', country: 'UG' },
  { text: 'Burundi', code: '+257', country: 'BI' },
  { text: 'Mozambique', code: '+258', country: 'MZ' },
  { text: 'Zambia', code: '+260', country: 'ZM' },
  { text: 'Madagascar', code: '+261', country: 'MG' },
  { text: 'Reunion', code: '+262', country: 'RE' },
  { text: 'Zimbabwe', code: '+263', country: 'ZW' },
  { text: 'Namibia', code: '+264', country: 'NA' },
  { text: 'Malawi', code: '+265', country: 'MW' },
  { text: 'Lesotho', code: '+266', country: 'LS' },
  { text: 'Botswana', code: '+267', country: 'BW' },
  { text: 'Eswatini', code: '+268', country: 'SZ' },
  { text: 'Comoros', code: '+269', country: 'KM' },
  { text: 'Saint Helena', code: '+290', country: 'SH' },
  { text: 'Eritrea', code: '+291', country: 'ER' },
  { text: 'Aruba', code: '+297', country: 'AW' },
  { text: 'Faroe Islands', code: '+298', country: 'FO' },
  { text: 'Greenland', code: '+299', country: 'GL' },
  { text: 'Gibraltar', code: '+350', country: 'GI' },
  { text: 'Portugal', code: '+351', country: 'PT' },
  { text: 'Luxembourg', code: '+352', country: 'LU' },
  { text: 'Ireland', code: '+353', country: 'IE' },
  { text: 'Iceland', code: '+354', country: 'IS' },
  { text: 'Albania', code: '+355', country: 'AL' },
  { text: 'Malta', code: '+356', country: 'MT' },
  { text: 'Cyprus', code: '+357', country: 'CY' },
  { text: 'Finland', code: '+358', country: 'FI' },
  { text: 'Bulgaria', code: '+359', country: 'BG' },
  { text: 'Lithuania', code: '+370', country: 'LT' },
  { text: 'Latvia', code: '+371', country: 'LV' },
  { text: 'Estonia', code: '+372', country: 'EE' },
  { text: 'Moldova', code: '+373', country: 'MD' },
  { text: 'Armenia', code: '+374', country: 'AM' },
  { text: 'Belarus', code: '+375', country: 'BY' },
  { text: 'Andorra', code: '+376', country: 'AD' },
  { text: 'Monaco', code: '+377', country: 'MC' },
  { text: 'San Marino', code: '+378', country: 'SM' },
  { text: 'Ukraine', code: '+380', country: 'UA' },
  { text: 'Serbia', code: '+381', country: 'RS' },
  { text: 'Montenegro', code: '+382', country: 'ME' },
  { text: 'Croatia', code: '+385', country: 'HR' },
  { text: 'Slovenia', code: '+386', country: 'SI' },
  { text: 'Bosnia and Herzegovina', code: '+387', country: 'BA' },
  { text: 'North Macedonia', code: '+389', country: 'MK' },
  { text: 'Czech Republic', code: '+420', country: 'CZ' },
  { text: 'Slovakia', code: '+421', country: 'SK' },
  { text: 'Liechtenstein', code: '+423', country: 'LI' },
  { text: 'Falkland Islands', code: '+500', country: 'FK' },
  { text: 'Belize', code: '+501', country: 'BZ' },
  { text: 'Guatemala', code: '+502', country: 'GT' },
  { text: 'El Salvador', code: '+503', country: 'SV' },
  { text: 'Honduras', code: '+504', country: 'HN' },
  { text: 'Nicaragua', code: '+505', country: 'NI' },
  { text: 'Costa Rica', code: '+506', country: 'CR' },
  { text: 'Panama', code: '+507', country: 'PA' },
  { text: 'Saint Pierre and Miquelon', code: '+508', country: 'PM' },
  { text: 'Haiti', code: '+509', country: 'HT' },
  { text: 'Guadeloupe', code: '+590', country: 'GP' },
  { text: 'Bolivia', code: '+591', country: 'BO' },
  { text: 'Guyana', code: '+592', country: 'GY' },
  { text: 'Ecuador', code: '+593', country: 'EC' },
  { text: 'French Guiana', code: '+594', country: 'GF' },
  { text: 'Paraguay', code: '+595', country: 'PY' },
  { text: 'Martinique', code: '+596', country: 'MQ' },
  { text: 'Suriname', code: '+597', country: 'SR' },
  { text: 'Uruguay', code: '+598', country: 'UY' },
  { text: 'Curaçao', code: '+599', country: 'CW' },
  { text: 'Timor-Leste', code: '+670', country: 'TL' },
  { text: 'Antarctica', code: '+672', country: 'AQ' },
  { text: 'Brunei', code: '+673', country: 'BN' },
  { text: 'Nauru', code: '+674', country: 'NR' },
  { text: 'Papua New Guinea', code: '+675', country: 'PG' },
  { text: 'Tonga', code: '+676', country: 'TO' },
  { text: 'Solomon Islands', code: '+677', country: 'SB' },
  { text: 'Vanuatu', code: '+678', country: 'VU' },
  { text: 'Fiji', code: '+679', country: 'FJ' },
  { text: 'Palau', code: '+680', country: 'PW' },
  { text: 'Wallis and Futuna', code: '+681', country: 'WF' },
  { text: 'Cook Islands', code: '+682', country: 'CK' },
  { text: 'Niue', code: '+683', country: 'NU' },
  { text: 'Samoa', code: '+685', country: 'WS' },
  { text: 'Kiribati', code: '+686', country: 'KI' },
  { text: 'New Caledonia', code: '+687', country: 'NC' },
  { text: 'Tuvalu', code: '+688', country: 'TV' },
  { text: 'French Polynesia', code: '+689', country: 'PF' },
  { text: 'Tokelau', code: '+690', country: 'TK' },
  {
    text: 'Federated States of Micronesia',
    code: '+691',
    country: 'FM',
  },
  { text: 'Marshall Islands', code: '+692', country: 'MH' },
  { text: 'North Korea', code: '+850', country: 'KP' },
  { text: 'Hong Kong', code: '+852', country: 'HK' },
  { text: 'Macau', code: '+853', country: 'MO' },
  { text: 'Cambodia', code: '+855', country: 'KH' },
  { text: 'Laos', code: '+856', country: 'LA' },
  { text: 'Bangladesh', code: '+880', country: 'BD' },
  { text: 'Taiwan', code: '+886', country: 'TW' },
  { text: 'Maldives', code: '+960', country: 'MV' },
  { text: 'Lebanon', code: '+961', country: 'LB' },
  { text: 'Jordan', code: '+962', country: 'JO' },
  { text: 'Syria', code: '+963', country: 'SY' },
  { text: 'Iraq', code: '+964', country: 'IQ' },
  { text: 'Kuwait', code: '+965', country: 'KW' },
  { text: 'Saudi Arabia', code: '+966', country: 'SA' },
  { text: 'Yemen', code: '+967', country: 'YE' },
  { text: 'Oman', code: '+968', country: 'OM' },
  { text: 'Palestine', code: '+970', country: 'PS' },
  { text: 'United Arab Emirates', code: '+971', country: 'AE' },
  { text: 'Israel', code: '+972', country: 'IL' },
  { text: 'Bahrain', code: '+973', country: 'BH' },
  { text: 'Qatar', code: '+974', country: 'QA' },
  { text: 'Bhutan', code: '+975', country: 'BT' },
  { text: 'Mongolia', code: '+976', country: 'MN' },
  { text: 'Nepal', code: '+977', country: 'NP' },
  { text: 'Tajikistan', code: '+992', country: 'TJ' },
  { text: 'Turkmenistan', code: '+993', country: 'TM' },
  { text: 'Azerbaijan', code: '+994', country: 'AZ' },
  { text: 'Georgia', code: '+995', country: 'GE' },
  { text: 'Kyrgyzstan', code: '+996', country: 'KG' },
  { text: 'Uzbekistan', code: '+998', country: 'UZ' },
];
